options: {}
engine:
  isready_lock_template: "{DNN_Model}.{DNN_Batch_Size}.serialized"
  isready_lock_check_templates:
    - "{DNN_Model}.*.{DNN_Batch_Size}*.serialized"
    - "{DNN_Model2}.*.{DNN_Batch_Size2}*.serialized"
    - "{DNN_Model3}.*.{DNN_Batch_Size3}*.serialized"
    - "{DNN_Model4}.*.{DNN_Batch_Size4}*.serialized"
    - "{DNN_Model5}.*.{DNN_Batch_Size5}*.serialized"
    - "{DNN_Model6}.*.{DNN_Batch_Size6}*.serialized"
    - "{DNN_Model7}.*.{DNN_Batch_Size7}*.serialized"
    - "{DNN_Model8}.*.{DNN_Batch_Size8}*.serialized"
  isready_lock_skip_if_exists: true
