"""N-engine native tournament orchestrator for arena tournaments.

This orchestrator consumes a game schedule and executes each game
using engine pooling and parallel execution.
"""

import asyncio
import hashlib
import json
import logging
import re
import sys
from collections.abc import Callable, Mapping
from datetime import datetime, timezone

import rshogi.record
import yaml
from rshogi.core import normalize_usi_position

from shogiarena.arena.configs.tournament import EngineConfig, GameSpec, TournamentRunConfig
from shogiarena.arena.engines.time_control import TimeControlLimits
from shogiarena.arena.instances.models import Instance, InstanceActiveGameSide
from shogiarena.arena.instances.pool import ResourceRequest
from shogiarena.arena.services.persistence.records import serialize_participation_records
from shogiarena.arena.session import GameCompletionEvent, GameLifecycleHooks, SessionContext
from shogiarena.utils.types.coerce import coerce_int
from shogiarena.utils.types.types import JsonValue

from .base_orchestrator import BaseOrchestrator, DashboardServerProtocol, SummaryUpdateCallback
from .base_orchestrator_utils import (
    build_engine_config_map,
    build_remote_game_info,
    build_time_control_limits,
    build_usi_options,
    enqueue_progress_event,
    make_role_pool_key,
    max_plies_from_rules,
    numeric_game_id,
)

logger = logging.getLogger(__name__)


class TournamentOrchestrator(BaseOrchestrator):
    """Orchestrates scheduled games from the tournament runner.

    This orchestrator is N-engine native and consumes a list of GameSpec
    objects generated by the tournament runner.
    """

    def __init__(
        self,
        config: TournamentRunConfig,
        *,
        session: SessionContext,
        hooks: GameLifecycleHooks,
        summary_updater: SummaryUpdateCallback | None = None,
        api_server: DashboardServerProtocol | None = None,  # Optional API server for SSE broadcasting
        cancelled_provider: Callable[[], set[str]] | None = None,
    ) -> None:
        """Initialize tournament orchestrator.

        Args:
            config: Tournament configuration
            session: Runner-prepared session context (run dir, workers, pool)
            hooks: Lifecycle hooks supplied by the runner
            summary_updater: Optional coroutine used to refresh dashboard summary
            api_server: Optional API server for SSE broadcasting
        """
        super().__init__(
            api_server=api_server,
            summary_updater=summary_updater,
            session_context=session,
            hooks=hooks,
            resource_poll_interval=config.system.resource_poll_interval,
            resource_poll_max_interval=config.system.resource_poll_max_interval,
        )
        self.config = config
        self.run_dir = session.storage.run_dir
        self.num_workers = session.num_workers
        # api_server is stored by BaseOrchestrator; no reassignment needed here

        # Prepare engine configurations
        self.engine_configs = self._prepare_engine_configs()
        # Initialize EnginePool
        self.engine_pool = self.create_engine_pool(self.num_workers)

        # Schedule state (set by runner before run())
        self._schedule: list[GameSpec] = []
        self._completed_game_ids: set[str] = set()
        self._cancelled_provider = cancelled_provider
        self._display_order_map: dict[str, int] = {}
        self._pending_queue: asyncio.PriorityQueue[tuple[int, int, GameSpec | None]] | None = None
        self._pending_queue_counter = 0

        # Initialize common components (progress, workers, game_runner, extra options)
        self._initialize_common_components(
            num_workers=self.num_workers,
            engines=config.engines,
            rules=config.rules,
            start_progress=True,
        )

    def set_schedule(self, schedule: list[GameSpec], completed: set[str]) -> None:
        """Provide game schedule and completed set prior to run()."""
        self._schedule = list(schedule)
        self._completed_game_ids = set(completed)
        self._display_order_map = {spec.game_id: idx for idx, spec in enumerate(self._schedule)}

    async def run(self) -> None:
        """Unified public entrypoint for runners.

        Expects schedule to be set via set_schedule() when used by the tournament runner.
        """
        cancelled = self._cancelled_provider() if self._cancelled_provider else set()
        pending = [
            spec
            for spec in self._schedule
            if spec.game_id not in self._completed_game_ids and spec.game_id not in cancelled
        ]

        if not pending:
            logger.debug("No pending games to run")
            return

        logger.debug(f"Running {len(pending)} pending games with {self.num_workers} parallel slots")

        self._pending_queue = asyncio.PriorityQueue()
        self._pending_queue_counter = 0
        for spec in pending:
            await self._enqueue_pending_game(spec)

        await self._consume_pending_games(concurrency_limit=self.num_workers)
        self._pending_queue = None
        ep = self.engine_pool
        assert ep is not None
        await ep.shutdown_all()

    async def _enqueue_pending_game(self, spec: GameSpec, *, display_order: int | None = None) -> None:
        queue = self._pending_queue
        if queue is None:
            return
        if display_order is None:
            display_order = self._display_order_map.get(spec.game_id)
        if display_order is None:
            display_order = len(self._display_order_map)
        self._pending_queue_counter += 1
        await queue.put((display_order, self._pending_queue_counter, spec))

    async def _consume_pending_games(self, *, concurrency_limit: int) -> None:
        queue = self._pending_queue
        if queue is None:
            return

        semaphore = asyncio.Semaphore(concurrency_limit)

        async def worker() -> None:
            while True:
                priority, counter, spec = await queue.get()
                if spec is None:
                    queue.task_done()
                    break

                cancelled_ids = self._cancelled_provider() if self._cancelled_provider else set()
                if spec.game_id in cancelled_ids:
                    queue.task_done()
                    continue

                await semaphore.acquire()

                async def _invoke(target: GameSpec) -> None:
                    await self._run_game(target)

                task: asyncio.Task[None] = asyncio.create_task(_invoke(spec))
                self._running_tasks.add(task)
                try:
                    await task
                finally:
                    self._running_tasks.discard(task)
                    semaphore.release()
                    queue.task_done()

        workers = [asyncio.create_task(worker()) for _ in range(concurrency_limit)]
        self._worker_tasks.update(workers)

        await queue.join()
        for _ in workers:
            self._pending_queue_counter += 1
            await queue.put((sys.maxsize, self._pending_queue_counter, None))

        await asyncio.gather(*workers)
        for w in workers:
            self._worker_tasks.discard(w)

    async def enqueue_restored_game(self, spec: GameSpec, display_order: int) -> None:
        if spec.game_id not in {existing.game_id for existing in self._schedule}:
            inserted = False
            for idx, existing in enumerate(self._schedule):
                current_order = self._display_order_map.get(existing.game_id, idx)
                if current_order > display_order:
                    self._schedule.insert(idx, spec)
                    inserted = True
                    break
            if not inserted:
                self._schedule.append(spec)
        self._display_order_map[spec.game_id] = display_order
        await self._enqueue_pending_game(spec, display_order=display_order)

    def _prepare_engine_configs(self) -> dict[str, EngineConfig]:
        """Ensure each engine has a concrete YAML; synthesize from artifact if needed."""
        out_entries: list[EngineConfig] = []
        cfg_out_dir = self.run_dir / "engine_configs"
        for e in self.config.engines:
            # Ensure overlay-provided engine settings (e.g., isready_lock_*) are applied
            # before writing out the engine config YAML.
            build_usi_options(getattr(self, "extra_options", None), e)
            if e.engine_path is not None and e.engine_path.exists():
                out_entries.append(e)
                continue

            art = e.artifact
            if art and art.strip():
                bopts = e.build_options or {}
                # Derive短いファイル名: commit + 安定化ハッシュ
                m = re.match(r"^([A-Za-z0-9._-]+)/([A-Fa-f0-9]{6,40})$", art.strip())

                def _normalize_for_hash(value: JsonValue) -> JsonValue:
                    match value:
                        case dict():
                            return {str(k): _normalize_for_hash(value[k]) for k in sorted(value)}
                        case list() | tuple():
                            return [_normalize_for_hash(v) for v in value]
                        case _:
                            return value

                normalized_payload = {
                    "artifact": art.strip(),
                    "build_options": _normalize_for_hash(dict(bopts)),
                }
                raw = json.dumps(normalized_payload, sort_keys=True, separators=(",", ":"), default=str)
                hash_suffix = hashlib.sha1(raw.encode("utf-8")).hexdigest()[:8]
                repo = m.group(1).lower() if m else "artifact"
                commit = m.group(2).lower() if m else None
                fname = f"{repo}_{commit}_{hash_suffix}.yaml" if commit else f"{repo}_{hash_suffix}.yaml"
                y: dict[str, object] = {"artifact": art, "build_options": dict(bopts)}
                if e.name:
                    y["name"] = e.name
                if e.mate_default_ply_limit is not None and e.mate_default_ply_limit > 0:
                    y["mate_default_ply_limit"] = e.mate_default_ply_limit
                if e.mate_default_node_limit is not None and e.mate_default_node_limit > 0:
                    y["mate_default_node_limit"] = e.mate_default_node_limit
                y["mate_default_infinite"] = e.mate_default_infinite
                y["mate_wait_for_bestmove"] = e.mate_wait_for_bestmove
                if e.isready_sync_strategy:
                    y["isready_sync_strategy"] = e.isready_sync_strategy
                if e.isready_lock_key and e.isready_lock_key.strip():
                    y["isready_lock_key"] = e.isready_lock_key.strip()
                if e.isready_lock_template and e.isready_lock_template.strip():
                    y["isready_lock_template"] = e.isready_lock_template.strip()
                if e.isready_lock_check_key and e.isready_lock_check_key.strip():
                    y["isready_lock_check_key"] = e.isready_lock_check_key.strip()
                if e.isready_lock_check_template and e.isready_lock_check_template.strip():
                    y["isready_lock_check_template"] = e.isready_lock_check_template.strip()
                if e.isready_lock_check_templates:
                    y["isready_lock_check_templates"] = [str(item) for item in e.isready_lock_check_templates]
                y["isready_lock_skip_if_exists"] = e.isready_lock_skip_if_exists
                if e.handshake_timeout is not None:
                    y["handshake_timeout"] = float(e.handshake_timeout)
                cfg_out_dir.mkdir(parents=True, exist_ok=True)
                out_path = cfg_out_dir / fname
                out_path.write_text(yaml.safe_dump(y, sort_keys=False), encoding="utf-8")
                # Attach back
                e.engine_path = out_path
                out_entries.append(e)
                continue

            raise ValueError(f"Engine '{e.name or 'engine'}' must provide engine_path or artifact with build_options")

        return build_engine_config_map(out_entries)

    async def _run_game(self, game_spec: GameSpec) -> None:
        """Execute a scheduled game with deadlock prevention."""
        if self._cancelled_provider is not None:
            try:
                cancelled_ids = self._cancelled_provider()
            except (RuntimeError, ValueError, OSError) as exc:
                logger.warning(
                    "Failed to query cancelled games; proceeding with %s: %s",
                    game_spec.game_id,
                    exc,
                    exc_info=True,
                )
            else:
                if game_spec.game_id in cancelled_ids:
                    logger.debug("Skipping cancelled game %s", game_spec.game_id)
                    return

        logger.debug(
            "Starting game %s: %s vs %s",
            game_spec.game_id,
            game_spec.black_engine,
            game_spec.white_engine,
        )

        # Pre-assign worker for this game to ensure stable mapping and remember index
        numeric_id = numeric_game_id(game_spec.game_id)
        preassigned_worker = self.preassign_worker(numeric_id, self.num_workers, self.game_to_worker, self.worker_busy)

        # Prepare items and time controls
        black_item, white_item, black_limits, white_limits = self._prepare_game_items(game_spec)
        progress_q = self.progress_queue
        if progress_q is not None:
            initial_sfen = normalize_usi_position(game_spec.initial_sfen or "startpos")
            black_tc_spec = black_limits.to_spec_str() if black_limits is not None else None
            white_tc_spec = white_limits.to_spec_str() if white_limits is not None else None
            enqueue_progress_event(
                progress_q,
                game_spec.game_id,
                {
                    "type": "game_assigned",
                    "game_id": game_spec.game_id,
                    "initial_sfen": initial_sfen,
                    "black_name": str(game_spec.black_engine),
                    "white_name": str(game_spec.white_engine),
                    "time_control_black": black_tc_spec,
                    "time_control_white": white_tc_spec,
                },
                fallback_move_count=0,
                allow_default_str=True,
            )

        pool = self.instance_pool
        b_spec = self.engine_configs.get(game_spec.black_engine)
        w_spec = self.engine_configs.get(game_spec.white_engine)
        default_black_id = b_spec.instance_id if b_spec is not None else None
        default_white_id = w_spec.instance_id if w_spec is not None else None
        black_instance_id = black_item.instance_override or default_black_id
        white_instance_id = white_item.instance_override or default_white_id

        # If both roles target the same SSH instance, run remotely for low latency
        same_instance_remote = False
        remote_instance = None
        if pool is not None and black_instance_id and white_instance_id and black_instance_id == white_instance_id:
            inst = pool.get_instance(black_instance_id)
            if inst is not None and inst.is_ssh:
                same_instance_remote = True
                remote_instance = inst

        if game_spec.require_install:
            await self._ensure_remote_install({black_instance_id, white_instance_id})
            game_spec.require_install = False

        if same_instance_remote and remote_instance is not None:
            game_info = await self._run_remote_pair_game(
                game_spec=game_spec,
                worker_idx=int(self.game_to_worker.get(numeric_id, 0)),
                black_limits=black_limits,
                white_limits=white_limits,
                remote_instance=remote_instance,
                black_item=black_item,
                white_item=white_item,
            )
        else:
            # Execute single game via shared helper (handles acquire/release)
            exec_spec = BaseOrchestrator.GameExecutionSpec(
                black_item=black_item,
                white_item=white_item,
                initial_sfen=game_spec.initial_sfen,
                game_id=game_spec.game_id,
                black_limits=black_limits,
                white_limits=white_limits,
                game_round=game_spec.round_num,
            )
            game_info = await self._execute_game(exec_spec)

        # Resolve worker index for completion broadcast (handle deferred preassignment)
        worker_idx = preassigned_worker if preassigned_worker is not None else self.game_to_worker.get(numeric_id, 0)

        event = GameCompletionEvent(
            game_id=game_spec.game_id,
            game_info=game_info,
            payload=game_spec,
            worker_idx=int(worker_idx) if worker_idx is not None else None,
            stop_requested=self._stop_event.is_set(),
        )
        await self._notify_game_complete(event)
        logger.debug("Game %s completed: %s", game_spec.game_id, game_info.result.value)

    async def _ensure_remote_install(self, instance_ids: set[str | None]) -> None:
        """Ensure remote instances have the arena repository prepared when requested."""
        pool = self.instance_pool
        if pool is None:
            return
        for inst_id in {i for i in instance_ids if i and i != "local"}:
            instance = pool.get_instance(inst_id)
            if instance is None or not instance.is_ssh:
                continue
            executor = self.get_remote_executor(instance)
            try:
                await self.ensure_remote_repo(executor, instance)
            except (RuntimeError, ValueError, OSError) as exc:
                logger.error("[%s] remote setup failed: %s", inst_id, exc, exc_info=True)
                raise

    async def _run_remote_pair_game(
        self,
        *,
        game_spec: GameSpec,
        worker_idx: int,
        black_limits: TimeControlLimits,
        white_limits: TimeControlLimits,
        remote_instance: Instance,
        black_item: BaseOrchestrator.EngineGameSpec,
        white_item: BaseOrchestrator.EngineGameSpec,
    ) -> rshogi.record.GameRecord:
        """Run a single scheduled game by executing both engines on the same SSH instance.

        Mirrors the SPSA remote runner path and streams JSON events back to the
        local progress queue for dashboard updates.
        """
        pool = self.instance_pool
        instance_id = remote_instance.name
        recorded_roles: list[InstanceActiveGameSide] = []
        resource_requirements: dict[str, ResourceRequest] = {}
        slots_reserved = False
        active_recorded = False
        if pool is not None and instance_id:
            resource_requirements = self._collect_instance_usage(pool, black_item, white_item)
            if resource_requirements:
                await self._await_instance_resources(pool, resource_requirements, game_spec.game_id)
                slots_reserved = True

        # Prepare names and options
        b_name = str(game_spec.black_engine)
        w_name = str(game_spec.white_engine)
        # Build per-engine options overlay (max-move sync handled separately by GameRunner)
        b_cfg_spec = self.engine_configs.get(b_name)
        w_cfg_spec = self.engine_configs.get(w_name)
        b_opts = build_usi_options(self.extra_options, b_cfg_spec) if b_cfg_spec is not None else {}
        w_opts = build_usi_options(self.extra_options, w_cfg_spec) if w_cfg_spec is not None else {}

        max_plies = max_plies_from_rules(self.config.rules)
        executor = None
        remote_root = None
        spec = None

        # Bridge streamed events to progress queue and aggregate per-move stats
        progress_q = self.progress_queue
        last_ply_seen = 0
        agg_moves: list[str] = []
        agg_move_times: list[int | None] = []
        agg_wall_times: list[int | None] = []
        agg_nodes: list[int | None] = []
        agg_depth: list[int | None] = []
        agg_seldepth: list[int | None] = []
        agg_evals: list[int | None] = []

        def _on_event(ev: dict[str, object]) -> None:
            nonlocal last_ply_seen
            if ev.get("type") == "move_progress":
                try:
                    ply = coerce_int(ev.get("ply")) or 0
                    last_ply_seen = max(last_ply_seen, ply)
                except (TypeError, ValueError):
                    # Keep prior last_ply_seen if payload is malformed
                    logger.debug("Malformed ply in event: %s", ev.get("ply"))
                move = ev.get("move")
                if isinstance(move, str) and move.strip():
                    agg_moves.append(move)
                    agg_evals.append(coerce_int(ev.get("eval_cp")))
                    agg_nodes.append(coerce_int(ev.get("nodes")))
                    agg_depth.append(coerce_int(ev.get("depth")))
                    agg_seldepth.append(coerce_int(ev.get("seldepth")))
                    agg_move_times.append(coerce_int(ev.get("time_ms")))
                    agg_wall_times.append(coerce_int(ev.get("wall_time_ms")))
            enqueue_progress_event(
                progress_q,
                game_spec.game_id,
                ev,
                fallback_move_count=last_ply_seen,
                allow_default_str=True,
            )

        # Info: start game
        logger.debug("[%s] start game %s: %s vs %s", remote_instance.name, game_spec.game_id, b_name, w_name)

        try:
            executor, remote_root, spec = await self._prepare_remote_game_spec(
                remote_instance=remote_instance,
                black_config_path=black_item.config_path,
                white_config_path=white_item.config_path,
                black_options=b_opts,
                white_options=w_opts,
                start_sfen=game_spec.initial_sfen,
                game_id=game_spec.game_id,
                black_name=b_name,
                white_name=w_name,
                black_limits=black_limits,
                white_limits=white_limits,
                max_plies=max_plies,
            )

            black_tc_spec = black_limits.to_spec_str() if black_limits is not None else None
            white_tc_spec = white_limits.to_spec_str() if white_limits is not None else None
            if pool is not None and instance_id:
                recorded_roles = [
                    InstanceActiveGameSide(role="black", engine_name=b_name, pool_key=black_item.pool_key),
                    InstanceActiveGameSide(role="white", engine_name=w_name, pool_key=white_item.pool_key),
                ]
                for role in recorded_roles:
                    pool.record_active_game(
                        instance_id,
                        game_id=game_spec.game_id,
                        black_engine=b_name,
                        white_engine=w_name,
                        initial_sfen=game_spec.initial_sfen,
                        role=role,
                        round_index=game_spec.round_num,
                        time_control_black=black_tc_spec,
                        time_control_white=white_tc_spec,
                    )
                active_recorded = True

            started_at = datetime.now(timezone.utc)
            events = await executor.run_remote_pair(remote_root=remote_root, spec=spec, on_event=_on_event)
        finally:
            if pool is not None and instance_id:
                if active_recorded:
                    pool.clear_active_game(instance_id, game_spec.game_id)
                if slots_reserved and resource_requirements:
                    pool.release_resources(resource_requirements)

        if spec is None:
            raise RuntimeError("Remote game spec was not prepared")

        # Extract final result code
        final_result = next(
            (
                e.get("result_code")
                for e in reversed(events)
                if isinstance(e, dict) and e.get("result_code") is not None
            ),
            None,
        )
        if final_result is None:
            raise RuntimeError("Remote game did not produce a result_code in move_progress events")

        # Build GameRecord from final

        gi = build_remote_game_info(
            start_sfen=game_spec.initial_sfen,
            moves=agg_moves,
            result_code=int(final_result),
            game_id=game_spec.game_id,
            black_name=b_name,
            white_name=w_name,
            black_limits=black_limits,
            white_limits=white_limits,
            move_times=agg_move_times,
            wall_times=agg_wall_times,
            nodes=agg_nodes,
            depth=agg_depth,
            seldepth=agg_seldepth,
            evals=agg_evals,
        )

        completed_at = datetime.now(timezone.utc)
        black_section_obj = spec.get("black") if isinstance(spec, dict) else None
        white_section_obj = spec.get("white") if isinstance(spec, dict) else None
        black_section: Mapping[str, object] = (
            {str(k): v for k, v in black_section_obj.items()} if isinstance(black_section_obj, Mapping) else {}
        )
        white_section: Mapping[str, object] = (
            {str(k): v for k, v in white_section_obj.items()} if isinstance(white_section_obj, Mapping) else {}
        )
        black_binary = black_section.get("engine_path")
        white_binary = white_section.get("engine_path")
        black_options_obj = black_section.get("options")
        white_options_obj = white_section.get("options")
        black_engine_options: Mapping[str, object] | None = (
            {str(k): v for k, v in black_options_obj.items()} if isinstance(black_options_obj, Mapping) else None
        )
        white_engine_options: Mapping[str, object] | None = (
            {str(k): v for k, v in white_options_obj.items()} if isinstance(white_options_obj, Mapping) else None
        )
        participation_records = [
            self._construct_participation_record(
                role="black",
                engine_name=b_name,
                display_name=b_name,
                spec=b_cfg_spec,
                engine_config=None,
                binary_path=str(black_binary) if isinstance(black_binary, str) else None,
                instance_id=instance_id,
                started_at=started_at,
                completed_at=completed_at,
                pool_key=black_item.pool_key,
                engine_options=black_engine_options,
                go_options=None,
                environment=None,
                engine_info=None,
            ),
            self._construct_participation_record(
                role="white",
                engine_name=w_name,
                display_name=w_name,
                spec=w_cfg_spec,
                engine_config=None,
                binary_path=str(white_binary) if isinstance(white_binary, str) else None,
                instance_id=instance_id,
                started_at=started_at,
                completed_at=completed_at,
                pool_key=white_item.pool_key,
                engine_options=white_engine_options,
                go_options=None,
                environment=None,
                engine_info=None,
            ),
        ]
        if participation_records:
            encoded = serialize_participation_records(participation_records)
            gi.set_metadata_attribute("_arena_participation", encoded)

        logger.debug(
            "[%s] end game %s: result=%s",
            remote_instance.name,
            game_spec.game_id,
            gi.result.value,
        )
        return gi

    def _prepare_game_items(
        self, game_spec: GameSpec
    ) -> tuple[
        BaseOrchestrator.EngineGameSpec,
        BaseOrchestrator.EngineGameSpec,
        TimeControlLimits,
        TimeControlLimits,
    ]:
        """Build engine items and per-side time control limits for a scheduled game.

        Returns (black_item, white_item, black_limits, white_limits).
        """
        black_config_spec = self.engine_configs.get(game_spec.black_engine)
        white_config_spec = self.engine_configs.get(game_spec.white_engine)
        if not black_config_spec or not white_config_spec:
            raise ValueError(f"Missing engine config for game {game_spec.game_id}")

        # Per-engine extra options (rules sync + overlays/options overrides)
        black_extras = build_usi_options(self.extra_options, black_config_spec)
        white_extras = build_usi_options(self.extra_options, white_config_spec)

        # Per-side time control limits (merge rules + per-engine overrides)
        base_tc = self.config.rules.time_control

        def pick_limits(spec: EngineConfig) -> TimeControlLimits:
            limits = build_time_control_limits(base_tc, spec.time_control)
            if limits is None:
                raise RuntimeError(
                    "Missing required time_control for tournament engine. "
                    "Provide rules.time_control or per-engine time_control."
                )
            return limits

        black_limits = pick_limits(black_config_spec)
        white_limits = pick_limits(white_config_spec)

        black_override = game_spec.assigned_instance_black
        white_override = game_spec.assigned_instance_white
        black_path = black_config_spec.engine_path
        white_path = white_config_spec.engine_path
        if black_path is None:
            raise ValueError(f"Engine '{game_spec.black_engine}' is missing a resolved engine_path")
        if white_path is None:
            raise ValueError(f"Engine '{game_spec.white_engine}' is missing a resolved engine_path")

        black_item = BaseOrchestrator.EngineGameSpec(
            pool_key=make_role_pool_key(game_spec.black_engine, "black"),
            config_path=black_path,
            extra_options=black_extras,
            instance_override=black_override,
            role="black",
        )
        white_item = BaseOrchestrator.EngineGameSpec(
            pool_key=make_role_pool_key(game_spec.white_engine, "white"),
            config_path=white_path,
            extra_options=white_extras,
            instance_override=white_override,
            role="white",
        )
        return black_item, white_item, black_limits, white_limits
