from __future__ import annotations

_BOUNDARY_ID_TOURNAMENT = "BND-RUNNER-STATE"
_BOUNDARY_ID_SPSA_INDEX = "BND-SPSA-INDEX"
_BOUNDARY_ID_SPSA = "BND-SPSA-RUN-STATE"

__all__ = [
    "_BOUNDARY_ID_SPSA",
    "_BOUNDARY_ID_SPSA_INDEX",
    "_BOUNDARY_ID_TOURNAMENT",
]
