from typing import TypeAlias

LK_UNLCK: int
LK_LOCK: int
LK_NBLCK: int
LK_RLCK: int
LK_NBRLCK: int

def locking(fd: int, mode: int, nbytes: int) -> None: ...
def get_osfhandle(fd: int) -> int: ...
def open_osfhandle(handle: int, flags: int) -> int: ...
def setmode(fd: int, flags: int) -> int: ...
def putch(char: bytes) -> bytes: ...
def putwch(char: str) -> str: ...
def getch() -> bytes: ...
def getwch() -> str: ...
def kbhit() -> int: ...

error: TypeAlias = OSError
