from typing import Any, TypeAlias

HKEY_CLASSES_ROOT: int
HKEY_CURRENT_USER: int
HKEY_LOCAL_MACHINE: int
HKEY_USERS: int
HKEY_CURRENT_CONFIG: int

REG_NONE: int
REG_SZ: int
REG_EXPAND_SZ: int
REG_BINARY: int
REG_DWORD: int
REG_DWORD_LITTLE_ENDIAN: int
REG_DWORD_BIG_ENDIAN: int
REG_LINK: int
REG_MULTI_SZ: int
REG_RESOURCE_LIST: int
REG_FULL_RESOURCE_DESCRIPTOR: int
REG_RESOURCE_REQUIREMENTS_LIST: int
REG_QWORD: int
REG_QWORD_LITTLE_ENDIAN: int

KEY_QUERY_VALUE: int
KEY_SET_VALUE: int
KEY_CREATE_SUB_KEY: int
KEY_ENUMERATE_SUB_KEYS: int
KEY_NOTIFY: int
KEY_CREATE_LINK: int
KEY_WOW64_64KEY: int
KEY_WOW64_32KEY: int
KEY_READ: int
KEY_WRITE: int
KEY_ALL_ACCESS: int

class PyHKEY(int):
    def Close(self) -> None: ...

HKEYType: TypeAlias = PyHKEY

error: TypeAlias = OSError

def ConnectRegistry(computer_name: str | None, key: int) -> PyHKEY: ...
def OpenKey(key: int | PyHKEY, sub_key: str, reserved: int = ..., access: int = ...) -> PyHKEY: ...
def OpenKeyEx(key: int | PyHKEY, sub_key: str, reserved: int = ..., access: int = ...) -> PyHKEY: ...
def CreateKey(key: int | PyHKEY, sub_key: str) -> PyHKEY: ...
def CreateKeyEx(key: int | PyHKEY, sub_key: str, reserved: int = ..., access: int = ...) -> PyHKEY: ...
def CloseKey(key: PyHKEY) -> None: ...
def QueryValue(key: PyHKEY, sub_key: str) -> str: ...
def QueryValueEx(key: PyHKEY, value_name: str) -> tuple[Any, int]: ...
def SetValue(key: PyHKEY, sub_key: str, type: int, value: str) -> None: ...
def SetValueEx(key: PyHKEY, value_name: str | None, reserved: int, type: int, value: Any) -> None: ...
def DeleteKey(key: PyHKEY, sub_key: str) -> None: ...
def DeleteKeyEx(key: PyHKEY, sub_key: str, reserved: int = ..., access: int = ...) -> None: ...
def DeleteValue(key: PyHKEY, value_name: str) -> None: ...
def EnumKey(key: PyHKEY, index: int) -> str: ...
def EnumValue(key: PyHKEY, index: int) -> tuple[str, Any, int]: ...
def QueryInfoKey(key: PyHKEY) -> tuple[int, int, int]: ...
def FlushKey(key: PyHKEY) -> None: ...
def LoadKey(key: PyHKEY, sub_key: str, file_name: str) -> None: ...
def SaveKey(key: PyHKEY, file_name: str) -> None: ...
def ExpandEnvironmentStrings(s: str) -> str: ...
def DisableReflectionKey(key: PyHKEY) -> None: ...
def EnableReflectionKey(key: PyHKEY) -> None: ...
def QueryReflectionKey(key: PyHKEY) -> bool: ...
