"""Type stubs for cshogi.elo module - Elo rating calculation"""

class Elo:
    """Elo rating calculator"""

    win: int
    lose: int
    draw: int

    def __init__(self, win: int = 0, lose: int = 0, draw: int = 0) -> None: ...
    @property
    def point_ratio(self) -> float: ...
    @property
    def error_margin(self) -> float: ...
    @property
    def difference(self) -> float: ...
    @property
    def draw_ratio(self) -> float: ...

def elo_diff(p: float) -> float: ...
def erf_inv(x: float) -> float: ...
def phi_inv(p: float) -> float: ...
