# やねうら王定義
MOVE_NONE = 0
MOVE_NULL = (1 << 7) + 1
MOVE_RESIGN = (2 << 7) + 2
MOVE_WIN = (3 << 7) + 3
# Database serialization constants
MOVE_END = (4 << 7) + 4
BANNED_PLAYER_RANK = -11111

MAX_PLY = 246
VALUE_ZERO = 0
VALUE_DRAW = 0
VALUE_NONE = 32002
VALUE_INFINITE = 32001
VALUE_MATE = 32000
VALUE_SUPERIOR = 28000
VALUE_MATE_IN_MAX_PLY = VALUE_MATE - MAX_PLY

REPETITION_NONE = 0
REPETITION_WIN = 1
REPETITION_LOSE = 2
REPETITION_DRAW = 3
REPETITION_SUPERIOR = 4
REPETITION_INFERIOR = 5
REPETITION_NB = 6

DRAW_VALUE_TABLE = [
    [VALUE_ZERO, VALUE_ZERO],  # REPETITION_NONE
    [VALUE_MATE, VALUE_MATE],  # REPETITION_WIN
    [-VALUE_MATE, -VALUE_MATE],  # REPETITION_LOSE
    [VALUE_DRAW, VALUE_DRAW],  # REPETITION_DRAW:  調整可能
    [VALUE_SUPERIOR, VALUE_SUPERIOR],  # REPETITION_SUPERIOR
    [-VALUE_SUPERIOR, -VALUE_SUPERIOR],  # REPETITION_INFERIOR
]


def get_draw_value(draw_type: int, color: int) -> int:
    return DRAW_VALUE_TABLE[draw_type][color]


# 手数(PLY)で詰ませるときのスコア
def mate_in(ply: int) -> int:
    return VALUE_MATE - ply


# 手数(PLY)で詰まされるときのスコア
def mated_in(ply: int) -> int:
    return -VALUE_MATE + ply
