name: Public CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "CHANGELOG.md"
      - "README*.md"
      - "docs/**"
      - "release-notes/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "CHANGELOG.md"
      - "README*.md"
      - "docs/**"
      - "release-notes/**"
  workflow_dispatch:

jobs:
  ci:
    if: github.repository == 'nyoki-mtl/ShogiArena'
    uses: ./.github/workflows/_ci-reusable.yml
    with:
      make_target: ci
